# Generated by Django 5.0.1 on 2024-04-10 14:56

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduSphere', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLS_SUBJ_MSTR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SCHOOL_ID', models.IntegerField()),
                ('CLASS_ID', models.IntegerField()),
                ('TeacherID', models.IntegerField()),
                ('SubjectID', models.IntegerField()),
                ('CR_DT', models.DateTimeField(verbose_name=datetime.datetime)),
                ('UP_DT', models.DateTimeField(verbose_name=datetime.datetime)),
            ],
        ),
        migrations.CreateModel(
            name='MstClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MstSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('image_path', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=100)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='EduSphere.mstclass')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='EduSphere.school')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubjectName', models.CharField(blank=True, max_length=50, null=True)),
                ('Credits', models.IntegerField(null=True)),
                ('image_path', models.CharField(blank=True, max_length=100, null=True)),
                ('Subject_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='EduSphere.mstclass')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduSphere.school')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('image_path', models.CharField(blank=True, max_length=100, null=True)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduSphere.school')),
            ],
        ),
    ]
