# Generated by Django 5.0.1 on 2024-04-12 07:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduSphere', '0002_cls_subj_mstr_mstclass_mstsubject_school_classes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='School',
            new_name='Schools',
        ),
        migrations.DeleteModel(
            name='Bore',
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='Credits',
            new_name='credits',
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='SubjectName',
            new_name='subject_name',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='Subject_ID',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='id',
        ),
        migrations.AlterField(
            model_name='cls_subj_mstr',
            name='CR_DT',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cls_subj_mstr',
            name='UP_DT',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='subject_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
